### ISSUE TITLE
new api for `$.taggedUnion` and `$.instance`

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/scale-ts#127]
Per discussion in #123, `$.option` will be changed to look like
```ts
const $foo = $.object(
  $.field("a", $.u8),
  $.field("b", $.str),
  $.optionalField("c", $.str),
)
```

How should `$.taggedUnion` and `$.instance` be updated to compensate?

At minimum, `$.taggedUnion` could be changed to
```ts
const $bar = $.taggedUnion("type", [
  ["A", $.field("x", $.u8), $.field("y", $.str)],
  ["B", $.field("val", $.bool)],
])
```

But the typing of this would likely be finicky. Alternatively...
```ts
const $bar = $.taggedUnion("type", [
  $.variant("A", $.field("x", $.u8), $.field("y", $.str)),
  $.variant("B", $.field("val", $.bool)),
])
```
This looks better IMO, but what is `$.variant(...)`?

Is it a codec whose metadata is treated specially?

Does it return some non-codec object that's then consumed by `$.taggedUnion`? We do have a general pattern that `$.foo` is a codec, but we do have `$.metadata`, so perhaps it's reasonable to have another exception.

Then, what about `$.instance`? At first glance it would seem like this would make sense:
```ts
class Bar {
  constructor(readonly a: number, readonly b: string) {}
}

const $bar = $.instance(
  Bar,
  $.field("a", $.u8),
  $.field("b", $.str),
)
```
But, taken literally, this is strange, as `$.field("a", $.u8)` decodes to `{ a: number }`, but we'd be passing the number directly to `Ctor`. And what if something other than a `$.field` is passed, like a `$.object`?

Perhaps instead it could like something like
```ts
const $bar = $.instance(
  Bar,
  $.tuple($.u8, $.str),
  bar => [bar.a, bar.b],
);
```
This feels perhaps a little less ergonomic, but it is less magical and more general. The `$.tuple` describes how to encode/decode the arguments to the constructor, and the arrow function describes how to extract the arguments from an instance.

Using `$.tuple` there means you could also use e.g. `$.array` or `$.sizedArray`, which I think is convenient.

**Comment by harrysolovay** [comment]
> What is $.variant(...)?

I suppose the `$.variant` factory could return a fn, which accepts the discriminant key (in this case `"type"`) and spreads the discriminant field (`{ type: "A" }` for instance) in with other fields of the given variant? The `$.taggedUnion` factory is responsible for applying the discriminant key to each variant?

In this sense, it's kind of a curried `$.field`?

> The $.tuple describes how to encode/decode the arguments to the constructor, and the arrow function describes how to extract the arguments from an instance.

This seems like the cleanest approach
