### ISSUE TITLE
improve performance of `$.object` et al with `new Function`

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/scale-ts#129]

**Comment by DanielZhangReal** [comment]
In chrome extensions, new Function has been explicitly forbidden. 
https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/#default-policy

More websites have opened CSP. like  github.com, twitter.com etc...

So can it be implemented without the ```new Function```?

**Comment by tjjfvi** [comment]
@DanielZhangReal Good point – #153
